export const MOCK_MENU_DATA = [
  {
    id: 1,
    restaurantId: 1,
    name: "Le Gourmet",
    cuisine: "French",
    createdAt: "2025-05-31T05:43:55.165Z",
    ageGroup: "All",
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836",
    rating: 4.9,
    numRatings: 320,
    availableTimes: ["breakfast", "lunch", "dinner"],
    categories: [
      {
        id: 2,
        menuId: 1,
        name: "Appetizers",
        position: 1,
        items: [
          {
            id: 2,
            categoryId: 2,
            name: "Foie Gras Terrine",
            description:
              "Traditional duck liver terrine with fig compote and toasted brioche.",
            price: 38,
            tags: ["gluten-free", "signature"],
            ingredients: ["duck liver", "fig", "brioche", "spices"],
            imageUrl:
              "https://images.unsplash.com/photo-1519864600265-abb23847ef2c",
            rating: 4.8,
            numRatings: 120,
            spiceLevel: 1,
            calories: 450,
            availableTimes: ["lunch", "dinner"],
            ageGroup: "Adults",
          },
          {
            id: 4,
            categoryId: 2,
            name: "Truffle Mushroom Risotto",
            description:
              "Creamy risotto with wild mushrooms, truffle oil, and parmesan.",
            price: 32,
            tags: ["vegetarian", "gluten-free", "signature"],
            ingredients: [
              "arborio rice",
              "wild mushrooms",
              "truffle oil",
              "parmesan",
              "cream",
            ],
            imageUrl:
              "https://images.unsplash.com/photo-1504674900247-0877df9cc836",
            rating: 4.9,
            numRatings: 110,
            spiceLevel: 1,
            calories: 540,
            availableTimes: ["lunch", "dinner"],
            ageGroup: "All",
          },
          {
            id: 5,
            categoryId: 2,
            name: "Chocolate Lava Cake",
            description:
              "Warm chocolate cake with a gooey molten center, served with vanilla ice cream.",
            price: 18,
            tags: ["vegetarian", "dessert"],
            ingredients: ["chocolate", "flour", "egg", "sugar", "butter"],
            imageUrl:
              "https://images.unsplash.com/photo-1519864600265-abb23847ef2c",
            rating: 4.7,
            numRatings: 90,
            spiceLevel: null,
            calories: 600,
            availableTimes: ["dinner"],
            ageGroup: "All",
          },
          {
            id: 6,
            categoryId: 2,
            name: "Edamame",
            description: "Steamed young soybeans with sea salt.",
            price: 8,
            tags: ["vegan", "gluten-free", "starter"],
            ingredients: ["edamame", "sea salt"],
            imageUrl:
              "https://images.unsplash.com/photo-1464306076886-debca5e8a6b0",
            rating: 4.6,
            numRatings: 60,
            spiceLevel: null,
            calories: 120,
            availableTimes: ["lunch", "dinner"],
            ageGroup: "All",
          },
          {
            id: 7,
            categoryId: 2,
            name: "Omakase Sushi Platter",
            description:
              "Chef's selection of the finest seasonal sushi and sashimi.",
            price: 55,
            tags: ["seafood", "signature"],
            ingredients: [
              "rice",
              "tuna",
              "salmon",
              "yellowtail",
              "shrimp",
              "octopus",
            ],
            imageUrl:
              "https://images.unsplash.com/photo-1464306076886-debca5e8a6b0",
            rating: 4.9,
            numRatings: 150,
            spiceLevel: 1,
            calories: 480,
            availableTimes: ["dinner"],
            ageGroup: "All",
          },
          {
            id: 8,
            categoryId: 2,
            name: "Miso Black Cod",
            description:
              "Black cod marinated in sweet miso, grilled to perfection.",
            price: 42,
            tags: ["seafood", "gluten-free"],
            ingredients: ["black cod", "miso", "sake", "mirin", "sugar"],
            imageUrl:
              "https://images.unsplash.com/photo-1464306076886-debca5e8a6b0",
            rating: 4.8,
            numRatings: 100,
            spiceLevel: 1,
            calories: 350,
            availableTimes: ["dinner"],
            ageGroup: "All",
          },
          {
            id: 9,
            categoryId: 2,
            name: "Burrata Caprese",
            description:
              "Creamy burrata cheese with heirloom tomatoes, basil, and olive oil.",
            price: 22,
            tags: ["vegetarian", "gluten-free"],
            ingredients: ["burrata", "tomato", "basil", "olive oil"],
            imageUrl:
              "https://images.unsplash.com/photo-1502741338009-cac2772e18bc",
            rating: 4.7,
            numRatings: 80,
            spiceLevel: null,
            calories: 320,
            availableTimes: ["lunch", "dinner"],
            ageGroup: "All",
          },
          {
            id: 10,
            categoryId: 2,
            name: "Handmade Tagliatelle with Truffle",
            description:
              "Fresh pasta with black truffle, parmesan, and cream sauce.",
            price: 36,
            tags: ["vegetarian", "signature"],
            ingredients: ["tagliatelle", "black truffle", "parmesan", "cream"],
            imageUrl:
              "https://images.unsplash.com/photo-1502741338009-cac2772e18bc",
            rating: 4.9,
            numRatings: 95,
            spiceLevel: 1,
            calories: 520,
            availableTimes: ["dinner"],
            ageGroup: "All",
          },
          {
            id: 11,
            categoryId: 2,
            name: "Tiramisu",
            description:
              "Classic Italian dessert with espresso-soaked ladyfingers and mascarpone cream.",
            price: 16,
            tags: ["vegetarian", "dessert"],
            ingredients: ["ladyfingers", "espresso", "mascarpone", "cocoa"],
            imageUrl:
              "https://images.unsplash.com/photo-1502741338009-cac2772e18bc",
            rating: 4.8,
            numRatings: 110,
            spiceLevel: null,
            calories: 420,
            availableTimes: ["dinner"],
            ageGroup: "All",
          },
        ],
      },
      {
        id: 3,
        menuId: 1,
        name: "Main Courses",
        position: 2,
        items: [],
      },
      {
        id: 4,
        menuId: 1,
        name: "Desserts",
        position: 3,
        items: [],
      },
    ],
  },
  {
    id: 2,
    restaurantId: 1,
    name: "Sakura",
    cuisine: "Japanese",
    createdAt: "2025-05-31T05:56:53.672Z",
    ageGroup: "All",
    imageUrl: "https://images.unsplash.com/photo-1464306076886-debca5e8a6b0",
    rating: 4.8,
    numRatings: 210,
    availableTimes: ["lunch", "dinner"],
    categories: [
      {
        id: 5,
        menuId: 2,
        name: "Starters",
        position: 1,
        items: [],
      },
      {
        id: 6,
        menuId: 2,
        name: "Sushi & Sashimi",
        position: 2,
        items: [],
      },
      {
        id: 7,
        menuId: 2,
        name: "Hot Dishes",
        position: 3,
        items: [],
      },
    ],
  },
  {
    id: 3,
    restaurantId: 1,
    name: "Trattoria Bella",
    cuisine: "Italian",
    createdAt: "2025-05-31T05:57:05.811Z",
    ageGroup: "All",
    imageUrl: "https://images.unsplash.com/photo-1502741338009-cac2772e18bc",
    rating: 4.7,
    numRatings: 180,
    availableTimes: ["lunch", "dinner"],
    categories: [
      {
        id: 8,
        menuId: 3,
        name: "Antipasti",
        position: 1,
        items: [],
      },
      {
        id: 9,
        menuId: 3,
        name: "Pasta",
        position: 2,
        items: [],
      },
      {
        id: 10,
        menuId: 3,
        name: "Dolci",
        position: 3,
        items: [],
      },
    ],
  },
];
